export type CultureCode = 'jp' | 'fr' | 'ae' | 'th' | 'it' | 'au'

export type CultureCard = {
  icon: string
  title: string
  color: 'pink' | 'blue'
  items: string[]
}

export type CultureDestination = {
  code: CultureCode
  name: string
  flag: string
  intro: string
  cards: CultureCard[]
}

export const CULTURE_DATA: Record<CultureCode, CultureDestination> = {
  jp: {
    code: 'jp',
    name: 'Japan',
    flag: '🗾',
    intro:
      'Konnichiwa. Japan balances precision, politeness, and group awareness, so even small gestures like lowering your voice, lining up neatly, and handling shared spaces carefully will make interactions feel much smoother and warmer.',
    cards: [
      {
        icon: '🗣️',
        title: 'Key Phrases',
        color: 'pink',
        items: [
          'Konnichiwa (Hello / good afternoon)',
          'Ohayo gozaimasu (Good morning)',
          'Konbanwa (Good evening)',
          'Arigatou gozaimasu (Thank you very much)',
          'Sumimasen (Excuse me / sorry / get attention)',
          'Onegaishimasu (Please, often when requesting service)',
          'Daijoubu desu (It is okay / no thank you)',
          'Eigo o hanasemasu ka? (Do you speak English?)',
        ],
      },
      {
        icon: '🙏',
        title: "Cultural Do's",
        color: 'blue',
        items: [
          'Queue carefully and follow platform markings in stations',
          'Remove shoes in homes, many ryokan, some temples, and fitting rooms',
          'Use both hands when giving business cards, cash, or gifts when possible',
          'Keep your phone on silent and speak quietly on public transit',
          'Stand to one side on escalators when locals do the same',
          'Carry a small bag for trash since public bins can be limited',
          'Bow lightly in polite situations even if you are also speaking',
          'Be on time; punctuality is taken seriously for tours, trains, and reservations',
        ],
      },
      {
        icon: '🚫',
        title: "Cultural Don'ts",
        color: 'pink',
        items: [
          'Do not eat while walking in places where locals generally avoid it',
          'Do not stick chopsticks upright into rice or pass food chopstick-to-chopstick',
          'Do not blow your nose loudly at the table',
          'Do not tip unless a venue clearly caters to international norms',
          'Do not enter onsen baths before washing thoroughly',
          'Do not touch merchandise casually in traditional shops unless invited',
          'Do not block narrow sidewalks or station pathways with luggage',
          'Do not assume direct confrontation is the best way to solve a problem',
        ],
      },
      {
        icon: '🍜',
        title: 'Dining Norms',
        color: 'blue',
        items: [
          'Many restaurants provide water and oshibori towels automatically',
          'Ramen slurping is normal and not considered rude',
          'You may need to order from a vending machine before sitting in some ramen shops',
          'Splitting bills is less common in smaller local places, so be ready to pay together',
          'Convenience stores have excellent quick meals and polite service culture',
          'Some restaurants specialize narrowly, so long menus are not always expected',
          'Reservations matter for high-demand sushi, kaiseki, and omakase spots',
          'Cash is still useful at smaller eateries despite growing card acceptance',
        ],
      },
      {
        icon: '🚆',
        title: 'Transit And Everyday Habits',
        color: 'pink',
        items: [
          'Trains are extremely reliable, so platform signs and car numbers matter',
          'Priority seats should be respected, especially around elderly passengers',
          'Backpacks are often worn on the front in crowded trains',
          'Keep luggage compact on urban transit during rush hour if you can',
          'IC cards like Suica or PASMO make city transit and convenience-store purchases easier',
          'Convenience stores, lockers, and train stations are part of daily life infrastructure',
          'Silence and efficiency in shared spaces are seen as considerate',
          'Google Maps works well, but station exits can still be confusing, so check the exit number',
        ],
      },
      {
        icon: '🚨',
        title: 'Emergency And Practical',
        color: 'blue',
        items: [
          'Police: 110',
          'Ambulance / Fire: 119',
          'Carry your passport or a legal copy if your accommodation allows it',
          'Many clinics may ask for payment up front before insurance reimbursement',
          'Earthquake alerts can appear on phones and public screens; stay calm and follow staff guidance',
          'Last trains can be earlier than visitors expect after nightlife',
          'Having your hotel name in Japanese can help with taxis',
          'If you lose something, ask station staff quickly; lost-and-found systems are strong',
        ],
      },
    ],
  },
  fr: {
    code: 'fr',
    name: 'France',
    flag: '🗼',
    intro:
      'Bonjour. In France, social etiquette starts with acknowledging people properly, and the overall rhythm is a little more formal and a little less rushed than many visitors expect, especially in shops, cafes, and meals.',
    cards: [
      {
        icon: '🗣️',
        title: 'Key Phrases',
        color: 'pink',
        items: [
          'Bonjour (Hello / good day)',
          'Bonsoir (Good evening)',
          'Merci beaucoup (Thank you very much)',
          "S'il vous plait (Please)",
          'Excusez-moi (Excuse me)',
          'Parlez-vous anglais ? (Do you speak English?)',
          "L'addition, s'il vous plait (The bill, please)",
          'Ou sont les toilettes ? (Where is the bathroom?)',
        ],
      },
      {
        icon: '🙏',
        title: "Cultural Do's",
        color: 'blue',
        items: [
          'Say bonjour before asking for help in shops, bakeries, and hotels',
          'Use monsieur, madame, or mademoiselle when appropriate in polite interactions',
          'Dress a bit more put-together in cities, especially in nicer restaurants',
          'Keep your speaking volume moderate on transit and in public indoor spaces',
          'Learn basic greetings even if the rest of the conversation happens in English',
          'Expect meals to be taken seriously and not treated as a rushed pit stop',
          'Validate metro tickets where required and keep them until the end of your ride',
          'Book museums and major attractions ahead during peak season',
        ],
      },
      {
        icon: '🚫',
        title: "Cultural Don'ts",
        color: 'pink',
        items: [
          'Do not skip the initial greeting and jump straight into a request',
          'Do not expect stores and pharmacies to keep the same hours as North America',
          'Do not assume every restaurant serves food continuously all afternoon',
          'Do not speak extra loudly to compensate for a language gap',
          'Do not expect immediate check delivery unless you ask for it',
          'Do not place your feet on metro seats or treat public spaces casually',
          'Do not rely on Sunday shopping outside tourist-heavy zones',
          'Do not treat bread, cheese, and wine traditions as a joke with staff who care deeply about them',
        ],
      },
      {
        icon: '🍷',
        title: 'Dining Norms',
        color: 'blue',
        items: [
          'Service is usually included, with small extra change left only for especially good service',
          'Longer meals are normal, especially at lunch and dinner',
          'You usually ask for the bill rather than receiving it automatically',
          'A cafe can be used for lingering, people-watching, and conversation',
          'Bread may arrive without butter by default and is often placed directly on the table',
          'Set menus at lunch can offer excellent value',
          'Coffee culture is different from full to-go culture; espresso is common, giant takeaway drinks are less central',
          'Dinner service often starts later than visitors expect, especially in southern Europe',
        ],
      },
      {
        icon: '🚇',
        title: 'City Rhythm And Public Life',
        color: 'pink',
        items: [
          'Metro systems are efficient but can involve many stairs, so pack accordingly',
          'Pickpocket awareness matters in crowded tourist corridors and train stations',
          'Street terraces are a major part of daily social life, especially in warmer months',
          'Many neighborhoods become quiet overnight outside nightlife districts',
          'Open-air markets can be some of the best places to experience local routine',
          'Personal space in lines can feel tighter in dense urban areas',
          'Protests and strikes happen periodically and are part of civic culture',
          'Museum and monument visits are often more enjoyable with timed-entry planning',
        ],
      },
      {
        icon: '🚨',
        title: 'Emergency And Practical',
        color: 'blue',
        items: [
          'Police: 17',
          'SAMU medical emergency: 15',
          'Fire: 18',
          'European emergency number: 112',
          'Validate transit passes properly to avoid surprise fines',
          'Carry some ID and a card with your hotel address',
          'Watch your belongings closely on intercity trains and in stations',
          'Pharmacies are often the first stop for minor medical advice and are easy to identify by the green cross',
        ],
      },
    ],
  },
  ae: {
    code: 'ae',
    name: 'UAE',
    flag: '🕌',
    intro:
      'Marhaba. The UAE is highly international, but public behavior still sits inside a more conservative social framework, so modesty, respect, and awareness of local laws matter far more than many tourists first assume.',
    cards: [
      {
        icon: '🗣️',
        title: 'Key Phrases',
        color: 'pink',
        items: [
          'Marhaba (Hello)',
          'As-salamu alaykum (Peace be upon you)',
          'Wa alaykum as-salam (Response to the greeting)',
          'Shukran (Thank you)',
          'Afwan (You are welcome / excuse me)',
          'Min fadlak / fadlik (Please)',
          'Kam al-sir? (How much is it?)',
          'Ayna...? (Where is...?)',
        ],
      },
      {
        icon: '🙏',
        title: "Cultural Do's",
        color: 'blue',
        items: [
          'Dress modestly in malls, old districts, mosques, and government spaces',
          'Use your right hand when offering food, money, or greetings when practical',
          'Ask before photographing people, especially women and families',
          'Respect prayer times and quiet behavior near mosques',
          'Adapt your behavior during Ramadan, particularly around eating and drinking in public',
          'Follow venue-specific dress codes in hotels, beach clubs, and fine dining spaces',
          'Be polite and measured with staff; public scenes reflect poorly',
          'Carry identification, especially in nightlife-heavy areas or while driving',
        ],
      },
      {
        icon: '🚫',
        title: "Cultural Don'ts",
        color: 'pink',
        items: [
          'Do not show public drunkenness or disorderly behavior',
          'Do not assume every beach, pool, or public space follows the same dress expectations',
          'Do not take photos of government buildings, security areas, or strangers casually',
          'Do not use insulting gestures or aggressive language during disputes',
          'Do not display intense public affection outside clearly tourist-oriented spaces',
          'Do not play loud music or act rowdy in residential areas late at night',
          'Do not make jokes about religion, rulers, or local customs',
          'Do not ignore signage; rules are often enforced more strictly than in other tourist hubs',
        ],
      },
      {
        icon: '🍽️',
        title: 'Dining And Hospitality',
        color: 'blue',
        items: [
          'Hospitality is a major cultural value, so offers of tea, coffee, or dates are meaningful',
          'Friday brunch culture is famous in larger cities and often more social than visitors expect',
          'Upscale dining is common, but modest neighborhood restaurants can be excellent',
          'During Ramadan, dining hours and restaurant availability can shift significantly',
          'In mixed international groups, dining etiquette can vary widely by venue',
          'Tipping is appreciated in many service settings even when service charges appear',
          'Water, shade, and air conditioning are part of daily survival planning in hotter months',
          'Book popular restaurants and desert experiences ahead in peak season',
        ],
      },
      {
        icon: '🏙️',
        title: 'Everyday Practical Norms',
        color: 'pink',
        items: [
          'Malls function as social, dining, and leisure hubs in addition to shopping spaces',
          'Ride-hailing is widely used and often easier than navigating on foot in extreme heat',
          'The local week and business rhythm may differ from what some visitors expect',
          'Luxury presentation can coexist with strict legal expectations',
          'Old souks and modern districts follow very different social tones',
          'Air-conditioned indoor walking is a major part of daily life in hot weather',
          'Respect private family space at parks, beaches, and majlis-style gatherings',
          'Plan outdoor sightseeing early morning or near sunset for comfort',
        ],
      },
      {
        icon: '🚨',
        title: 'Emergency And Practical',
        color: 'blue',
        items: [
          'Police: 999',
          'Ambulance: 998',
          'Fire: 997',
          'Coast Guard: 996',
          'Heat exhaustion is a real risk; hydrate before you feel thirsty',
          'Carry your hotel name and address in English and Arabic if possible',
          'Traffic can be fast-paced, so use official crossings rather than improvising',
          'Local laws on substances, medication, and behavior can be strict, so check what you bring',
        ],
      },
    ],
  },
  th: {
    code: 'th',
    name: 'Thailand',
    flag: '🏯',
    intro:
      'Sawasdee. Thailand is warm and welcoming, but social harmony matters a lot, so calm speech, respect for sacred spaces, and sensitivity around hierarchy and public composure will usually get you much farther than forceful behavior.',
    cards: [
      {
        icon: '🗣️',
        title: 'Key Phrases',
        color: 'pink',
        items: [
          'Sawasdee krab / ka (Hello)',
          'Khob khun krab / ka (Thank you)',
          'Chai (Yes)',
          'Mai chai (No)',
          'Tao rai? (How much?)',
          'Hong nam yoo tee nai? (Where is the bathroom?)',
          'Aroy mak (Very delicious)',
          'Kor toht (Sorry / excuse me)',
        ],
      },
      {
        icon: '🙏',
        title: "Cultural Do's",
        color: 'blue',
        items: [
          'Return a wai greeting when appropriate, especially in more formal or respectful situations',
          'Dress with covered shoulders and knees for temples',
          'Remove shoes before entering temples, some homes, and certain indoor spaces',
          'Stay calm, smile, and keep public interactions low-conflict',
          'Treat monks, shrines, and Buddha images with visible respect',
          'Carry small cash for markets, street food, and local transport',
          'Use a soft tone when negotiating or correcting misunderstandings',
          'Respect the head as symbolically important and the feet as symbolically low',
        ],
      },
      {
        icon: '🚫',
        title: "Cultural Don'ts",
        color: 'pink',
        items: [
          'Do not touch someone on the head, including children',
          'Do not point your feet at people, altars, or Buddha images',
          'Do not climb on religious statues for photos',
          'Do not raise your voice publicly if service is slow or confusing',
          'Do not speak lightly or critically about the monarchy',
          'Do not enter temples in beachwear or revealing clothes',
          'Do not assume smiles always mean agreement; they may signal politeness or discomfort',
          'Do not disrespect local spirit houses, offerings, or rituals even if you do not understand them',
        ],
      },
      {
        icon: '🍜',
        title: 'Food And Market Culture',
        color: 'blue',
        items: [
          'Street food is central to daily life and often excellent, not just a tourist novelty',
          'Spice levels can be much stronger than visitors expect, so ask before ordering',
          'Shared dishes are common in group meals',
          'Night markets are as much a social experience as a place to eat',
          'Cash is still very useful outside upscale malls and hotels',
          'Ice in drinks is common and normal at many reputable vendors',
          'Food courts in malls can offer reliable, affordable local meals',
          'Look for busy stalls with fast turnover when choosing street food',
        ],
      },
      {
        icon: '🛺',
        title: 'Transit And Everyday Rhythm',
        color: 'pink',
        items: [
          'Bangkok traffic can be intense, so rail transit often beats road travel',
          'Tuk-tuks are fun but fares should be discussed before the ride',
          'Ride-hailing apps are often simpler than flagging taxis on the street',
          'Island and beach destinations operate on slower timelines than the capital',
          'Temple visits are quieter early in the day before the heat builds',
          'Bargaining can happen in markets, but keep it friendly and light',
          'Shoes that are easy to remove are practical for temple-heavy days',
          'Humidity and heat can drain you faster than expected, so build in breaks',
        ],
      },
      {
        icon: '🚨',
        title: 'Emergency And Practical',
        color: 'blue',
        items: [
          'Police: 191',
          'Ambulance / medical emergency: 1669',
          'Tourist Police: 1155',
          'Keep your hotel card for taxis and late-night returns',
          'Use mosquito repellent consistently, especially near water or in rainy periods',
          'Motorbike accidents are common, so be cautious about rentals and helmets',
          'ATM fees can be high, so plan cash withdrawals strategically',
          'Watch for common tourist scams around transport, gem shops, and overly eager tour offers',
        ],
      },
    ],
  },
  it: {
    code: 'it',
    name: 'Italy',
    flag: '🍕',
    intro:
      'Ciao. Italy tends to reward travellers who slow down, greet people properly, and treat food, neighborhood rhythm, and historic spaces with respect rather than trying to consume everything at top speed.',
    cards: [
      {
        icon: '🗣️',
        title: 'Key Phrases',
        color: 'pink',
        items: [
          'Ciao (Hi / bye, informal)',
          'Buongiorno (Good morning / good day)',
          'Buonasera (Good evening)',
          'Grazie mille (Thank you very much)',
          'Per favore (Please)',
          'Scusi (Excuse me)',
          'Parla inglese? (Do you speak English?)',
          'Il conto, per favore (The bill, please)',
        ],
      },
      {
        icon: '🙏',
        title: "Cultural Do's",
        color: 'blue',
        items: [
          'Use greetings before requests in shops, cafes, and hotels',
          'Dress respectfully when entering churches, cathedrals, and religious sites',
          'Book major museums and landmarks ahead, especially in Rome, Florence, and Venice',
          'Take time over meals and enjoy the local pacing',
          'Validate train or transit tickets when required',
          'Ask for the bill when you are ready rather than expecting it automatically',
          'Learn a few Italian phrases; effort is appreciated even in tourist zones',
          'Keep some cash for smaller bars, taxis, or neighborhood stores',
        ],
      },
      {
        icon: '🚫',
        title: "Cultural Don'ts",
        color: 'pink',
        items: [
          'Do not sit on church steps or monuments as if they are casual benches',
          'Do not assume every cafe functions like a laptop workspace',
          'Do not rush service staff during peak meal periods',
          'Do not expect cappuccino culture to work the same all day in every local bar',
          'Do not ignore pickpocket risk around major stations and tourist areas',
          'Do not enter sacred sites in beachwear or overly bare clothing',
          'Do not order heavily customized dishes in very traditional restaurants and expect enthusiasm',
          'Do not treat historical centers as theme parks; many are still lived-in neighborhoods',
        ],
      },
      {
        icon: '🍝',
        title: 'Dining Norms',
        color: 'blue',
        items: [
          'Coffee at the counter is often quicker and cheaper than table service',
          'Coperto or service charges may appear on the bill and are normal in many places',
          'Dinner commonly starts later than in North America',
          'Regional food identity is strong, so local specialties matter a lot',
          'A simple neighborhood trattoria can be better than a famous tourist spot',
          'Courses are often paced separately: antipasti, primi, secondi, dolci',
          'Bread is usually for the meal itself, not automatically for dipping in olive oil',
          'Gelato quality varies, so look for natural colors and covered tins when possible',
        ],
      },
      {
        icon: '🚄',
        title: 'Transit And Daily Rhythm',
        color: 'pink',
        items: [
          'High-speed rail makes city-to-city travel easier than driving in many routes',
          'Historic centers can involve lots of walking on uneven stone streets',
          'Afternoon slowdowns or closures still happen in some towns and family-run businesses',
          'ZTL restricted traffic zones can create major fines for drivers',
          'Italian cities come alive in the evening, especially during passeggiata time',
          'Market mornings are great for seeing local routine beyond monuments',
          'Late-night returns can depend heavily on your exact neighborhood',
          'Comfortable shoes matter more than stylish ones once you hit cobblestones',
        ],
      },
      {
        icon: '🚨',
        title: 'Emergency And Practical',
        color: 'blue',
        items: [
          'General emergency: 112',
          'Ambulance: 118',
          'Fire: 115',
          'Carry a copy of your accommodation address for taxis and train arrivals',
          'Watch bags closely in crowded stations, buses, and attraction queues',
          'Church bells, late dinners, and evening social life can shape the soundscape differently from home',
          'Public fountains in many cities provide drinkable water, but check local signage',
          'Reserve timed-entry attractions early to avoid wasting prime sightseeing hours in line',
        ],
      },
    ],
  },
  au: {
    code: 'au',
    name: 'Australia',
    flag: '🦘',
    intro:
      "G'day. Australia can feel relaxed and informal, but that easygoing style sits alongside serious expectations around safety, weather, nature, and customs rules, so practical awareness matters just as much as social confidence.",
    cards: [
      {
        icon: '🗣️',
        title: 'Key Phrases',
        color: 'pink',
        items: [
          "G'day (Hello)",
          'No worries (It is fine / no problem)',
          'Arvo (Afternoon)',
          'Brekkie (Breakfast)',
          'Cheers (Thanks / goodbye in casual use)',
          'How ya going? (How are you?)',
          'Servo (Gas station)',
          'Takeaway (To-go food)',
        ],
      },
      {
        icon: '🙏',
        title: "Cultural Do's",
        color: 'blue',
        items: [
          'Declare all food, plant, and animal products at customs honestly',
          'Use sunscreen, hats, and water even on cloudy days',
          'Swim between red-and-yellow flags on patrolled beaches',
          'Respect Acknowledgement of Country when present at events or institutions',
          'Be straightforward, friendly, and not overly formal in conversation',
          'Tip modestly only when service is genuinely strong; it is not mandatory in the same way as the US',
          'Check bushfire, surf, or wildlife conditions when travelling regionally',
          'Carry reusable water and plan for long distances between stops outside cities',
        ],
      },
      {
        icon: '🚫',
        title: "Cultural Don'ts",
        color: 'pink',
        items: [
          'Do not underestimate UV levels or outdoor dehydration',
          'Do not bring undeclared snacks, seeds, or fresh food through the border',
          'Do not swim at unpatrolled beaches if you do not understand local conditions',
          'Do not treat wildlife as safe for feeding, touching, or close selfies',
          'Do not assume urban public transit patterns apply in rural or regional areas',
          'Do not drive long distances without checking fuel, reception, and weather conditions',
          'Do not ignore warning signs about rips, jellyfish, crocodiles, or bushfire zones',
          'Do not mistake casual language for lack of seriousness around rules',
        ],
      },
      {
        icon: '🍽️',
        title: 'Food And Social Habits',
        color: 'blue',
        items: [
          'Cafe culture is strong, especially in Melbourne, Sydney, and coastal towns',
          'Flat whites, long blacks, and brunch menus are part of mainstream daily life',
          'BYO restaurants exist and can be great value, but check corkage rules',
          'Barbecues, outdoor eating, and beach picnics are part of the social rhythm',
          'Portion expectations and tipping culture differ from the US',
          'Pub meals are common and often family-friendly outside late-night hours',
          'Regional produce, seafood, and multicultural food scenes are major highlights',
          'Booking ahead helps in popular urban dining districts and holiday towns',
        ],
      },
      {
        icon: '🚗',
        title: 'Distances And Daily Practicality',
        color: 'pink',
        items: [
          'Australia is huge, so domestic flights often save more time than visitors expect',
          'Driving is on the left and regional roads can feel very isolated',
          'City centers are easy to navigate, but suburbs can sprawl widely',
          'Public transit quality varies a lot by city and region',
          'Weather can shift quickly from intense heat to cool evenings depending on location',
          'School holidays and long weekends can change pricing and crowd levels dramatically',
          'Phone coverage can disappear outside populated corridors',
          'Beach, outback, and city travel all require different packing strategies',
        ],
      },
      {
        icon: '🚨',
        title: 'Emergency And Practical',
        color: 'blue',
        items: [
          'Emergency: 000',
          'Police non-emergency: 131 444',
          'Poisons Information: 13 11 26',
          'Watch for heatstroke, surf hazards, and road fatigue on long drives',
          'If hiking, tell someone your route and carry more water than you think you need',
          'Quarantine rules are strict, so keep receipts and packaging for declared items if needed',
          'Regional medical help can be far away, so plan remote trips carefully',
          'Local warnings about weather and wildlife are there for a reason; take them literally',
        ],
      },
    ],
  },
}
